# This is a basic workflow to help you get started with Actions

name: test-pipe

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-2022

    env:
      # default env paths
      POSTGRES_HOME: 'C:\Program Files\PostgreSQL\15'
      POSTGRES_VERSION: 15.2

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # maintain cache of PostgreSQL installation
      - name: Cache Postgres
        id: cache-postgres
        uses: actions/cache@v3
        with:
         path: ${{ env.POSTGRES_HOME }}
         key: ${{ runner.os }}-postgres-15
         restore-keys: ${{ runner.os }}-postgres-15

       # Set postgres path
      - name: Set path
        run: echo "${{ env.POSTGRES_HOME }}\bin" | Out-File -FilePath $ENV:GITHUB_PATH -Encoding utf8 -Append

      # Install Postgres SQL 
      - name: Install Postgres
        if: ${{steps.cache-postgres.outputs.cache-hit != 'true'}} # condition to check if old installation is available in cache
        shell: powershell
        run: choco install postgresql -y --version=${{ env.POSTGRES_VERSION }} 

      # Runs a set of commands using the runners shell
      - name: version check
        shell: powershell
        run: 'postgres -V'

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        shell: powershell
        run: 'Get-ChildItem -Path Env:'